# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nextrun/nextrun.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="nextrun/nextrun.proto",
    package="nextrun",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x15nextrun/nextrun.proto\x12\x07nextrun"\xcc\x01\n\x10RunPyFuncRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x18\n\x10interpreter_path\x18\x02 \x01(\t\x12\x12\n\ncode_paths\x18\x03 \x03(\t\x12\x13\n\x0bmodule_name\x18\x04 \x01(\t\x12\x15\n\rfunction_name\x18\x05 \x01(\t\x12"\n\x1apickled_function_arguments\x18\x06 \x01(\x0c\x12&\n\x1eresult_highest_pickle_protocol\x18\x07 \x01(\x05"+\n\x14ProcessStatesRequest\x12\x13\n\x0brequest_ids\x18\x01 \x03(\t"\xbc\x02\n\x0cProcessState\x12\x35\n\x05state\x18\x01 \x01(\x0e\x32&.nextrun.ProcessState.ProcessStateEnum\x12\x0b\n\x03pid\x18\x02 \x01(\x05\x12\x16\n\x0epickled_result\x18\x03 \x01(\x0c\x12\x13\n\x0breturn_code\x18\x04 \x01(\x05"\xba\x01\n\x10ProcessStateEnum\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\x18\n\x14REQUEST_IS_DUPLICATE\x10\x01\x12\x0b\n\x07UNKNOWN\x10\x02\x12\x17\n\x13\x45RROR_GETTING_STATE\x10\x03\x12\r\n\tSUCCEEDED\x10\x04\x12\x14\n\x10PYTHON_EXCEPTION\x10\x05\x12\x18\n\x14NON_ZERO_RETURN_CODE\x10\x06\x12\r\n\tCANCELLED\x10\x07\x12\x0b\n\x07RUNNING\x10\x08">\n\rProcessStates\x12-\n\x0eprocess_states\x18\x01 \x03(\x0b\x32\x15.nextrun.ProcessState2\xa1\x01\n\rNextRunServer\x12\x41\n\x0brun_py_func\x12\x19.nextrun.RunPyFuncRequest\x1a\x15.nextrun.ProcessState"\x00\x12M\n\x12get_process_states\x12\x1d.nextrun.ProcessStatesRequest\x1a\x16.nextrun.ProcessStates"\x00\x62\x06proto3',
)


_PROCESSSTATE_PROCESSSTATEENUM = _descriptor.EnumDescriptor(
    name="ProcessStateEnum",
    full_name="nextrun.ProcessState.ProcessStateEnum",
    filename=None,
    file=DESCRIPTOR,
    create_key=_descriptor._internal_create_key,
    values=[
        _descriptor.EnumValueDescriptor(
            name="DEFAULT",
            index=0,
            number=0,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="REQUEST_IS_DUPLICATE",
            index=1,
            number=1,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="UNKNOWN",
            index=2,
            number=2,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="ERROR_GETTING_STATE",
            index=3,
            number=3,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="SUCCEEDED",
            index=4,
            number=4,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="PYTHON_EXCEPTION",
            index=5,
            number=5,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="NON_ZERO_RETURN_CODE",
            index=6,
            number=6,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="CANCELLED",
            index=7,
            number=7,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="RUNNING",
            index=8,
            number=8,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=417,
    serialized_end=603,
)
_sym_db.RegisterEnumDescriptor(_PROCESSSTATE_PROCESSSTATEENUM)


_RUNPYFUNCREQUEST = _descriptor.Descriptor(
    name="RunPyFuncRequest",
    full_name="nextrun.RunPyFuncRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="request_id",
            full_name="nextrun.RunPyFuncRequest.request_id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="interpreter_path",
            full_name="nextrun.RunPyFuncRequest.interpreter_path",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="code_paths",
            full_name="nextrun.RunPyFuncRequest.code_paths",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="module_name",
            full_name="nextrun.RunPyFuncRequest.module_name",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="function_name",
            full_name="nextrun.RunPyFuncRequest.function_name",
            index=4,
            number=5,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="pickled_function_arguments",
            full_name="nextrun.RunPyFuncRequest.pickled_function_arguments",
            index=5,
            number=6,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="result_highest_pickle_protocol",
            full_name="nextrun.RunPyFuncRequest.result_highest_pickle_protocol",
            index=6,
            number=7,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=35,
    serialized_end=239,
)


_PROCESSSTATESREQUEST = _descriptor.Descriptor(
    name="ProcessStatesRequest",
    full_name="nextrun.ProcessStatesRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="request_ids",
            full_name="nextrun.ProcessStatesRequest.request_ids",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=241,
    serialized_end=284,
)


_PROCESSSTATE = _descriptor.Descriptor(
    name="ProcessState",
    full_name="nextrun.ProcessState",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="state",
            full_name="nextrun.ProcessState.state",
            index=0,
            number=1,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="pid",
            full_name="nextrun.ProcessState.pid",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="pickled_result",
            full_name="nextrun.ProcessState.pickled_result",
            index=2,
            number=3,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="return_code",
            full_name="nextrun.ProcessState.return_code",
            index=3,
            number=4,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[
        _PROCESSSTATE_PROCESSSTATEENUM,
    ],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=287,
    serialized_end=603,
)


_PROCESSSTATES = _descriptor.Descriptor(
    name="ProcessStates",
    full_name="nextrun.ProcessStates",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="process_states",
            full_name="nextrun.ProcessStates.process_states",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=605,
    serialized_end=667,
)

_PROCESSSTATE.fields_by_name["state"].enum_type = _PROCESSSTATE_PROCESSSTATEENUM
_PROCESSSTATE_PROCESSSTATEENUM.containing_type = _PROCESSSTATE
_PROCESSSTATES.fields_by_name["process_states"].message_type = _PROCESSSTATE
DESCRIPTOR.message_types_by_name["RunPyFuncRequest"] = _RUNPYFUNCREQUEST
DESCRIPTOR.message_types_by_name["ProcessStatesRequest"] = _PROCESSSTATESREQUEST
DESCRIPTOR.message_types_by_name["ProcessState"] = _PROCESSSTATE
DESCRIPTOR.message_types_by_name["ProcessStates"] = _PROCESSSTATES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RunPyFuncRequest = _reflection.GeneratedProtocolMessageType(
    "RunPyFuncRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _RUNPYFUNCREQUEST,
        "__module__": "nextrun.nextrun_pb2"
        # @@protoc_insertion_point(class_scope:nextrun.RunPyFuncRequest)
    },
)
_sym_db.RegisterMessage(RunPyFuncRequest)

ProcessStatesRequest = _reflection.GeneratedProtocolMessageType(
    "ProcessStatesRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _PROCESSSTATESREQUEST,
        "__module__": "nextrun.nextrun_pb2"
        # @@protoc_insertion_point(class_scope:nextrun.ProcessStatesRequest)
    },
)
_sym_db.RegisterMessage(ProcessStatesRequest)

ProcessState = _reflection.GeneratedProtocolMessageType(
    "ProcessState",
    (_message.Message,),
    {
        "DESCRIPTOR": _PROCESSSTATE,
        "__module__": "nextrun.nextrun_pb2"
        # @@protoc_insertion_point(class_scope:nextrun.ProcessState)
    },
)
_sym_db.RegisterMessage(ProcessState)

ProcessStates = _reflection.GeneratedProtocolMessageType(
    "ProcessStates",
    (_message.Message,),
    {
        "DESCRIPTOR": _PROCESSSTATES,
        "__module__": "nextrun.nextrun_pb2"
        # @@protoc_insertion_point(class_scope:nextrun.ProcessStates)
    },
)
_sym_db.RegisterMessage(ProcessStates)


_NEXTRUNSERVER = _descriptor.ServiceDescriptor(
    name="NextRunServer",
    full_name="nextrun.NextRunServer",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=670,
    serialized_end=831,
    methods=[
        _descriptor.MethodDescriptor(
            name="run_py_func",
            full_name="nextrun.NextRunServer.run_py_func",
            index=0,
            containing_service=None,
            input_type=_RUNPYFUNCREQUEST,
            output_type=_PROCESSSTATE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="get_process_states",
            full_name="nextrun.NextRunServer.get_process_states",
            index=1,
            containing_service=None,
            input_type=_PROCESSSTATESREQUEST,
            output_type=_PROCESSSTATES,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_NEXTRUNSERVER)

DESCRIPTOR.services_by_name["NextRunServer"] = _NEXTRUNSERVER

# @@protoc_insertion_point(module_scope)
