# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nextbeat/server/nextbeat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="nextbeat/server/nextbeat.proto",
    package="nextbeat",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x1enextbeat/server/nextbeat.proto\x12\x08nextbeat"1\n\x0e\x41\x64\x64JobsRequest\x12\x1f\n\x17pickled_job_definitions\x18\x01 \x01(\x0c"!\n\x0f\x41\x64\x64JobsResponse\x12\x0e\n\x06status\x18\x01 \x01(\t"2\n\x18InstantiateScopesRequest\x12\x16\n\x0epickled_scopes\x18\x01 \x01(\x0c"\x1b\n\x19InstantiateScopesResponse",\n\rEventsRequest\x12\x1b\n\x13pickled_topic_names\x18\x01 \x01(\x0c" \n\x06\x45vents\x12\x16\n\x0epickled_events\x18\x01 \x01(\x0c"D\n\x18RegisterJobRunnerRequest\x12\x17\n\x0fjob_runner_type\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t"\x1b\n\x19RegisterJobRunnerResponse",\n\x10ManualRunRequest\x12\x18\n\x10pickled_job_name\x18\x01 \x01(\x0c"\x13\n\x11ManualRunResponse2\x9a\x03\n\x0eNextBeatServer\x12\x41\n\x08\x61\x64\x64_jobs\x12\x18.nextbeat.AddJobsRequest\x1a\x19.nextbeat.AddJobsResponse"\x00\x12_\n\x12instantiate_scopes\x12".nextbeat.InstantiateScopesRequest\x1a#.nextbeat.InstantiateScopesResponse"\x00\x12\x39\n\nget_events\x12\x17.nextbeat.EventsRequest\x1a\x10.nextbeat.Events"\x00\x12`\n\x13register_job_runner\x12".nextbeat.RegisterJobRunnerRequest\x1a#.nextbeat.RegisterJobRunnerResponse"\x00\x12G\n\nmanual_run\x12\x1a.nextbeat.ManualRunRequest\x1a\x1b.nextbeat.ManualRunResponse"\x00\x62\x06proto3',
)


_ADDJOBSREQUEST = _descriptor.Descriptor(
    name="AddJobsRequest",
    full_name="nextbeat.AddJobsRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="pickled_job_definitions",
            full_name="nextbeat.AddJobsRequest.pickled_job_definitions",
            index=0,
            number=1,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=44,
    serialized_end=93,
)


_ADDJOBSRESPONSE = _descriptor.Descriptor(
    name="AddJobsResponse",
    full_name="nextbeat.AddJobsResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="status",
            full_name="nextbeat.AddJobsResponse.status",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=95,
    serialized_end=128,
)


_INSTANTIATESCOPESREQUEST = _descriptor.Descriptor(
    name="InstantiateScopesRequest",
    full_name="nextbeat.InstantiateScopesRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="pickled_scopes",
            full_name="nextbeat.InstantiateScopesRequest.pickled_scopes",
            index=0,
            number=1,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=130,
    serialized_end=180,
)


_INSTANTIATESCOPESRESPONSE = _descriptor.Descriptor(
    name="InstantiateScopesResponse",
    full_name="nextbeat.InstantiateScopesResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=182,
    serialized_end=209,
)


_EVENTSREQUEST = _descriptor.Descriptor(
    name="EventsRequest",
    full_name="nextbeat.EventsRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="pickled_topic_names",
            full_name="nextbeat.EventsRequest.pickled_topic_names",
            index=0,
            number=1,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=211,
    serialized_end=255,
)


_EVENTS = _descriptor.Descriptor(
    name="Events",
    full_name="nextbeat.Events",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="pickled_events",
            full_name="nextbeat.Events.pickled_events",
            index=0,
            number=1,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=257,
    serialized_end=289,
)


_REGISTERJOBRUNNERREQUEST = _descriptor.Descriptor(
    name="RegisterJobRunnerRequest",
    full_name="nextbeat.RegisterJobRunnerRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="job_runner_type",
            full_name="nextbeat.RegisterJobRunnerRequest.job_runner_type",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="address",
            full_name="nextbeat.RegisterJobRunnerRequest.address",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=291,
    serialized_end=359,
)


_REGISTERJOBRUNNERRESPONSE = _descriptor.Descriptor(
    name="RegisterJobRunnerResponse",
    full_name="nextbeat.RegisterJobRunnerResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=361,
    serialized_end=388,
)


_MANUALRUNREQUEST = _descriptor.Descriptor(
    name="ManualRunRequest",
    full_name="nextbeat.ManualRunRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="pickled_job_name",
            full_name="nextbeat.ManualRunRequest.pickled_job_name",
            index=0,
            number=1,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=390,
    serialized_end=434,
)


_MANUALRUNRESPONSE = _descriptor.Descriptor(
    name="ManualRunResponse",
    full_name="nextbeat.ManualRunResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=436,
    serialized_end=455,
)

DESCRIPTOR.message_types_by_name["AddJobsRequest"] = _ADDJOBSREQUEST
DESCRIPTOR.message_types_by_name["AddJobsResponse"] = _ADDJOBSRESPONSE
DESCRIPTOR.message_types_by_name["InstantiateScopesRequest"] = _INSTANTIATESCOPESREQUEST
DESCRIPTOR.message_types_by_name[
    "InstantiateScopesResponse"
] = _INSTANTIATESCOPESRESPONSE
DESCRIPTOR.message_types_by_name["EventsRequest"] = _EVENTSREQUEST
DESCRIPTOR.message_types_by_name["Events"] = _EVENTS
DESCRIPTOR.message_types_by_name["RegisterJobRunnerRequest"] = _REGISTERJOBRUNNERREQUEST
DESCRIPTOR.message_types_by_name[
    "RegisterJobRunnerResponse"
] = _REGISTERJOBRUNNERRESPONSE
DESCRIPTOR.message_types_by_name["ManualRunRequest"] = _MANUALRUNREQUEST
DESCRIPTOR.message_types_by_name["ManualRunResponse"] = _MANUALRUNRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddJobsRequest = _reflection.GeneratedProtocolMessageType(
    "AddJobsRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _ADDJOBSREQUEST,
        "__module__": "nextbeat.server.nextbeat_pb2"
        # @@protoc_insertion_point(class_scope:nextbeat.AddJobsRequest)
    },
)
_sym_db.RegisterMessage(AddJobsRequest)

AddJobsResponse = _reflection.GeneratedProtocolMessageType(
    "AddJobsResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _ADDJOBSRESPONSE,
        "__module__": "nextbeat.server.nextbeat_pb2"
        # @@protoc_insertion_point(class_scope:nextbeat.AddJobsResponse)
    },
)
_sym_db.RegisterMessage(AddJobsResponse)

InstantiateScopesRequest = _reflection.GeneratedProtocolMessageType(
    "InstantiateScopesRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _INSTANTIATESCOPESREQUEST,
        "__module__": "nextbeat.server.nextbeat_pb2"
        # @@protoc_insertion_point(class_scope:nextbeat.InstantiateScopesRequest)
    },
)
_sym_db.RegisterMessage(InstantiateScopesRequest)

InstantiateScopesResponse = _reflection.GeneratedProtocolMessageType(
    "InstantiateScopesResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _INSTANTIATESCOPESRESPONSE,
        "__module__": "nextbeat.server.nextbeat_pb2"
        # @@protoc_insertion_point(class_scope:nextbeat.InstantiateScopesResponse)
    },
)
_sym_db.RegisterMessage(InstantiateScopesResponse)

EventsRequest = _reflection.GeneratedProtocolMessageType(
    "EventsRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _EVENTSREQUEST,
        "__module__": "nextbeat.server.nextbeat_pb2"
        # @@protoc_insertion_point(class_scope:nextbeat.EventsRequest)
    },
)
_sym_db.RegisterMessage(EventsRequest)

Events = _reflection.GeneratedProtocolMessageType(
    "Events",
    (_message.Message,),
    {
        "DESCRIPTOR": _EVENTS,
        "__module__": "nextbeat.server.nextbeat_pb2"
        # @@protoc_insertion_point(class_scope:nextbeat.Events)
    },
)
_sym_db.RegisterMessage(Events)

RegisterJobRunnerRequest = _reflection.GeneratedProtocolMessageType(
    "RegisterJobRunnerRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _REGISTERJOBRUNNERREQUEST,
        "__module__": "nextbeat.server.nextbeat_pb2"
        # @@protoc_insertion_point(class_scope:nextbeat.RegisterJobRunnerRequest)
    },
)
_sym_db.RegisterMessage(RegisterJobRunnerRequest)

RegisterJobRunnerResponse = _reflection.GeneratedProtocolMessageType(
    "RegisterJobRunnerResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _REGISTERJOBRUNNERRESPONSE,
        "__module__": "nextbeat.server.nextbeat_pb2"
        # @@protoc_insertion_point(class_scope:nextbeat.RegisterJobRunnerResponse)
    },
)
_sym_db.RegisterMessage(RegisterJobRunnerResponse)

ManualRunRequest = _reflection.GeneratedProtocolMessageType(
    "ManualRunRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _MANUALRUNREQUEST,
        "__module__": "nextbeat.server.nextbeat_pb2"
        # @@protoc_insertion_point(class_scope:nextbeat.ManualRunRequest)
    },
)
_sym_db.RegisterMessage(ManualRunRequest)

ManualRunResponse = _reflection.GeneratedProtocolMessageType(
    "ManualRunResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _MANUALRUNRESPONSE,
        "__module__": "nextbeat.server.nextbeat_pb2"
        # @@protoc_insertion_point(class_scope:nextbeat.ManualRunResponse)
    },
)
_sym_db.RegisterMessage(ManualRunResponse)


_NEXTBEATSERVER = _descriptor.ServiceDescriptor(
    name="NextBeatServer",
    full_name="nextbeat.NextBeatServer",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=458,
    serialized_end=868,
    methods=[
        _descriptor.MethodDescriptor(
            name="add_jobs",
            full_name="nextbeat.NextBeatServer.add_jobs",
            index=0,
            containing_service=None,
            input_type=_ADDJOBSREQUEST,
            output_type=_ADDJOBSRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="instantiate_scopes",
            full_name="nextbeat.NextBeatServer.instantiate_scopes",
            index=1,
            containing_service=None,
            input_type=_INSTANTIATESCOPESREQUEST,
            output_type=_INSTANTIATESCOPESRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="get_events",
            full_name="nextbeat.NextBeatServer.get_events",
            index=2,
            containing_service=None,
            input_type=_EVENTSREQUEST,
            output_type=_EVENTS,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="register_job_runner",
            full_name="nextbeat.NextBeatServer.register_job_runner",
            index=3,
            containing_service=None,
            input_type=_REGISTERJOBRUNNERREQUEST,
            output_type=_REGISTERJOBRUNNERRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="manual_run",
            full_name="nextbeat.NextBeatServer.manual_run",
            index=4,
            containing_service=None,
            input_type=_MANUALRUNREQUEST,
            output_type=_MANUALRUNRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_NEXTBEATSERVER)

DESCRIPTOR.services_by_name["NextBeatServer"] = _NEXTBEATSERVER

# @@protoc_insertion_point(module_scope)
