site_name: Meadowrun
repo_url: https://github.com/meadowdata/meadowrun
edit_uri: edit/main/docs/
theme:
  name: material
  font:
    text: Source Sans Pro
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - search.suggest
extra_css:
  - extra.css
plugins:
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_root_heading: yes
            heading_level: 3
            show_source: no
  - search
  - awesome-pages
  - include-markdown
  - redirects:
      redirect_maps:
        'tutorial/install.md': 'index.md'
        'tutorial/run_function.md': 'tutorial/aws_ec2.md'
        'tutorial/run_function_git_conda.md': 'tutorial/deployment.md'
        'tutorial/run_command_in_container.md': 'tutorial/deployment.md'
        'tutorial/run_map.md': 'tutorial/entry_points.md'
        'how_to/kubernetes.md': 'tutorial/kubernetes.md'
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
