# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from meadowflow.server import (
    meadowflow_pb2 as meadowflow_dot_server_dot_meadowflow__pb2,
)


class MeadowFlowServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.add_jobs = channel.unary_unary(
            "/meadowflow.MeadowFlowServer/add_jobs",
            request_serializer=meadowflow_dot_server_dot_meadowflow__pb2.AddJobsRequest.SerializeToString,
            response_deserializer=meadowflow_dot_server_dot_meadowflow__pb2.AddJobsResponse.FromString,
        )
        self.instantiate_scopes = channel.unary_unary(
            "/meadowflow.MeadowFlowServer/instantiate_scopes",
            request_serializer=meadowflow_dot_server_dot_meadowflow__pb2.InstantiateScopesRequest.SerializeToString,
            response_deserializer=meadowflow_dot_server_dot_meadowflow__pb2.InstantiateScopesResponse.FromString,
        )
        self.get_events = channel.unary_unary(
            "/meadowflow.MeadowFlowServer/get_events",
            request_serializer=meadowflow_dot_server_dot_meadowflow__pb2.EventsRequest.SerializeToString,
            response_deserializer=meadowflow_dot_server_dot_meadowflow__pb2.Events.FromString,
        )
        self.register_job_runner = channel.unary_unary(
            "/meadowflow.MeadowFlowServer/register_job_runner",
            request_serializer=meadowflow_dot_server_dot_meadowflow__pb2.RegisterJobRunnerRequest.SerializeToString,
            response_deserializer=meadowflow_dot_server_dot_meadowflow__pb2.RegisterJobRunnerResponse.FromString,
        )
        self.manual_run = channel.unary_unary(
            "/meadowflow.MeadowFlowServer/manual_run",
            request_serializer=meadowflow_dot_server_dot_meadowflow__pb2.ManualRunRequest.SerializeToString,
            response_deserializer=meadowflow_dot_server_dot_meadowflow__pb2.ManualRunResponse.FromString,
        )


class MeadowFlowServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def add_jobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def instantiate_scopes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def get_events(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def register_job_runner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def manual_run(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MeadowFlowServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "add_jobs": grpc.unary_unary_rpc_method_handler(
            servicer.add_jobs,
            request_deserializer=meadowflow_dot_server_dot_meadowflow__pb2.AddJobsRequest.FromString,
            response_serializer=meadowflow_dot_server_dot_meadowflow__pb2.AddJobsResponse.SerializeToString,
        ),
        "instantiate_scopes": grpc.unary_unary_rpc_method_handler(
            servicer.instantiate_scopes,
            request_deserializer=meadowflow_dot_server_dot_meadowflow__pb2.InstantiateScopesRequest.FromString,
            response_serializer=meadowflow_dot_server_dot_meadowflow__pb2.InstantiateScopesResponse.SerializeToString,
        ),
        "get_events": grpc.unary_unary_rpc_method_handler(
            servicer.get_events,
            request_deserializer=meadowflow_dot_server_dot_meadowflow__pb2.EventsRequest.FromString,
            response_serializer=meadowflow_dot_server_dot_meadowflow__pb2.Events.SerializeToString,
        ),
        "register_job_runner": grpc.unary_unary_rpc_method_handler(
            servicer.register_job_runner,
            request_deserializer=meadowflow_dot_server_dot_meadowflow__pb2.RegisterJobRunnerRequest.FromString,
            response_serializer=meadowflow_dot_server_dot_meadowflow__pb2.RegisterJobRunnerResponse.SerializeToString,
        ),
        "manual_run": grpc.unary_unary_rpc_method_handler(
            servicer.manual_run,
            request_deserializer=meadowflow_dot_server_dot_meadowflow__pb2.ManualRunRequest.FromString,
            response_serializer=meadowflow_dot_server_dot_meadowflow__pb2.ManualRunResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "meadowflow.MeadowFlowServer", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class MeadowFlowServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def add_jobs(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/meadowflow.MeadowFlowServer/add_jobs",
            meadowflow_dot_server_dot_meadowflow__pb2.AddJobsRequest.SerializeToString,
            meadowflow_dot_server_dot_meadowflow__pb2.AddJobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def instantiate_scopes(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/meadowflow.MeadowFlowServer/instantiate_scopes",
            meadowflow_dot_server_dot_meadowflow__pb2.InstantiateScopesRequest.SerializeToString,
            meadowflow_dot_server_dot_meadowflow__pb2.InstantiateScopesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def get_events(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/meadowflow.MeadowFlowServer/get_events",
            meadowflow_dot_server_dot_meadowflow__pb2.EventsRequest.SerializeToString,
            meadowflow_dot_server_dot_meadowflow__pb2.Events.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def register_job_runner(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/meadowflow.MeadowFlowServer/register_job_runner",
            meadowflow_dot_server_dot_meadowflow__pb2.RegisterJobRunnerRequest.SerializeToString,
            meadowflow_dot_server_dot_meadowflow__pb2.RegisterJobRunnerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def manual_run(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/meadowflow.MeadowFlowServer/manual_run",
            meadowflow_dot_server_dot_meadowflow__pb2.ManualRunRequest.SerializeToString,
            meadowflow_dot_server_dot_meadowflow__pb2.ManualRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
