"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class AddJobsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PICKLED_JOB_DEFINITIONS_FIELD_NUMBER: builtins.int
    pickled_job_definitions: builtins.bytes = ...
    def __init__(
        self,
        *,
        pickled_job_definitions: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "pickled_job_definitions", b"pickled_job_definitions"
        ],
    ) -> None: ...

global___AddJobsRequest = AddJobsRequest

class AddJobsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    STATUS_FIELD_NUMBER: builtins.int
    status: typing.Text = ...
    def __init__(
        self,
        *,
        status: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["status", b"status"]
    ) -> None: ...

global___AddJobsResponse = AddJobsResponse

class InstantiateScopesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PICKLED_SCOPES_FIELD_NUMBER: builtins.int
    pickled_scopes: builtins.bytes = ...
    def __init__(
        self,
        *,
        pickled_scopes: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["pickled_scopes", b"pickled_scopes"]
    ) -> None: ...

global___InstantiateScopesRequest = InstantiateScopesRequest

class InstantiateScopesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    def __init__(
        self,
    ) -> None: ...

global___InstantiateScopesResponse = InstantiateScopesResponse

class EventsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PICKLED_TOPIC_NAMES_FIELD_NUMBER: builtins.int
    pickled_topic_names: builtins.bytes = ...
    def __init__(
        self,
        *,
        pickled_topic_names: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "pickled_topic_names", b"pickled_topic_names"
        ],
    ) -> None: ...

global___EventsRequest = EventsRequest

class Events(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PICKLED_EVENTS_FIELD_NUMBER: builtins.int
    pickled_events: builtins.bytes = ...
    def __init__(
        self,
        *,
        pickled_events: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["pickled_events", b"pickled_events"]
    ) -> None: ...

global___Events = Events

class RegisterJobRunnerRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    JOB_RUNNER_TYPE_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    job_runner_type: typing.Text = ...
    address: typing.Text = ...
    def __init__(
        self,
        *,
        job_runner_type: typing.Text = ...,
        address: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "address", b"address", "job_runner_type", b"job_runner_type"
        ],
    ) -> None: ...

global___RegisterJobRunnerRequest = RegisterJobRunnerRequest

class RegisterJobRunnerResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    def __init__(
        self,
    ) -> None: ...

global___RegisterJobRunnerResponse = RegisterJobRunnerResponse

class ManualRunRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PICKLED_JOB_NAME_FIELD_NUMBER: builtins.int
    PICKLED_JOB_RUN_OVERRIDES_FIELD_NUMBER: builtins.int
    pickled_job_name: builtins.bytes = ...
    pickled_job_run_overrides: builtins.bytes = ...
    def __init__(
        self,
        *,
        pickled_job_name: builtins.bytes = ...,
        pickled_job_run_overrides: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "pickled_job_name",
            b"pickled_job_name",
            "pickled_job_run_overrides",
            b"pickled_job_run_overrides",
        ],
    ) -> None: ...

global___ManualRunRequest = ManualRunRequest

class ManualRunResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    RUN_REQUEST_ID_FIELD_NUMBER: builtins.int
    run_request_id: typing.Text = ...
    def __init__(
        self,
        *,
        run_request_id: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["run_request_id", b"run_request_id"]
    ) -> None: ...

global___ManualRunResponse = ManualRunResponse
