apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: minio
  name: minio
spec:
  containers:
  - name: minio
    image: quay.io/minio/minio:latest
    args:
      - server
      - /root
      - --console-address
      - ":9090"
    env:
    - name: MINIO_ROOT_USER
      value: "ROOTNAME"
    - name: MINIO_ROOT_PASSWORD
      value: "CHANGEME123"
    ports:
    - containerPort: 9000
    - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: minio
  ports:
    - name: minio-main-port
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: minio-console-port
      protocol: TCP
      port: 9090
      targetPort: 9090